server:
  port: 8086

spring:
  application:
    name: budget-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: expense-cloud
      sentinel:
        transport:
          dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8858}
          port: 8726
        eager: true
